const S=[{id:'joker',i:'🃏',min:3,p:{3:800,4:8000,5:40000}},{id:'guitar',i:'🎸',min:3,p:{3:400,4:1600,5:8000}},{id:'bonus',i:'👑',min:3,p:{3:500,4:2000,5:10000},scatter:true},{id:'shoes',i:'👢',min:3,p:{3:200,4:400,5:1600}},{id:'blue',i:'🔵',min:2,p:{2:50,3:200,4:400,5:1600}},{id:'red',i:'♦️',min:3,p:{3:200,4:400,5:1600}}];
const L=[[[0,0],[1,0],[2,0],[3,0],[4,0]],[[0,1],[1,1],[2,1],[3,1],[4,1]],[[0,2],[1,2],[2,2],[3,2],[4,2]],[[0,0],[1,1],[2,2],[3,1],[4,0]],[[0,2],[1,1],[2,0],[3,1],[4,2]],[[0,0],[1,0],[2,1],[3,2],[4,2]],[[0,2],[1,2],[2,1],[3,0],[4,0]],[[0,1],[1,0],[2,0],[3,0],[4,1]],[[0,1],[1,2],[2,2],[3,2],[4,1]],[[0,0],[1,1],[2,1],[3,1],[4,0]]];
let bal=476126,bet=50,grid=[],busy=false,turbo=false,auto=false,autoT=null,sound=true;const bets=[50,100,250,500,1000,2500];const $=n=>'$ '+Math.round(n).toLocaleString('es-AR');
function openGame(){lobby.classList.remove('active');game.classList.add('active');drawPay();drawGrid();}
function backLobby(){stopAuto();game.classList.remove('active');lobby.classList.add('active')}
function drawPay(){paytable.innerHTML=S.map(s=>`<div class="payitem"><div class="sym">${s.i}</div>${Object.entries(s.p).reverse().map(([n,v])=>`${n} - ${$(v*bet/50)}`).join('<br>')}</div>`).join('');betTop.textContent=$(bet);document.getElementById('bet').textContent=$(bet)}
function random(){grid=Array.from({length:5},()=>Array.from({length:3},()=>S[Math.floor(Math.random()*S.length)].id))}
function drawGrid(h=[]){let set=new Set(h.map(x=>x.join('-')));reels.innerHTML=grid.map((col,c)=>`<div class="reel">${col.map((id,r)=>`<div class="cell ${set.has(c+'-'+r)?'hit':''}">${S.find(s=>s.id===id).i}</div>`).join('')}</div>`).join('')}
function evalWin(){let total=0,h=[];for(const line of L){let id=grid[line[0][0]][line[0][1]],s=S.find(x=>x.id===id);if(!s||s.scatter)continue;let n=1;for(let k=1;k<5;k++){let [c,r]=line[k];if(grid[c][r]===id)n++;else break}if(n>=s.min&&s.p[n]){total+=s.p[n]*bet/50;h.push(...line.slice(0,n))}}let bc=[];for(let c=0;c<5;c++)for(let r=0;r<3;r++)if(grid[c][r]==='bonus')bc.push([c,r]);if(bc.length>=3){let n=Math.min(5,bc.length),s=S.find(x=>x.id==='bonus');total+=(s.p[n]||s.p[5])*bet/50;h.push(...bc)}return{total,h}}
function spin(){if(busy||bal<bet)return;busy=true;bal-=bet;updateBal();win.textContent='GIRANDO…';gain.textContent='$ 0';let n=0,max=turbo?3:9,iv=setInterval(()=>{random();drawGrid();if(++n>=max){clearInterval(iv);finish()}},turbo?55:90)}
function finish(){let r=evalWin();bal+=r.total;updateBal();drawGrid(r.h);gain.textContent=$(r.total);win.innerHTML=r.total?`¡GANASTE!<b>${$(r.total)}</b>`:'SIN PREMIO';busy=false;if(r.total>=bet*20){bigAmount.textContent=$(r.total);overlay.classList.add('show')}else if(auto)autoT=setTimeout(spin,turbo?250:700)}
function closeWin(){overlay.classList.remove('show');if(auto&&!busy)autoT=setTimeout(spin,300)}
function changeBet(d){if(busy)return;let i=bets.indexOf(bet),j=Math.max(0,Math.min(bets.length-1,i+d));bet=bets[j];drawPay()}
function updateBal(){saldo.textContent=Math.round(bal).toLocaleString('es-AR')}
function toggleTurbo(){turbo=!turbo;document.getElementById('turbo').classList.toggle('on',turbo)}function toggleAuto(){auto=!auto;document.getElementById('auto').classList.toggle('on',auto);if(auto&&!busy)spin();else clearTimeout(autoT)}function stopAuto(){auto=false;clearTimeout(autoT);document.getElementById('auto').classList.remove('on')}function toggleSound(){sound=!sound;document.getElementById('sound').textContent=sound?'🔊 SONIDO':'🔇 SONIDO'}
random();drawGrid();drawPay();updateBal();
